INSERT INTO Food(id, name, idCategory) VALUES (?, ?, ?);
INSERT INTO Food_Category(id, name) VALUES (?, ?);
INSERT INTO Ingredient(idRecipe, idFood, quantity, unit) VALUES (?, ?, ?, ?);
INSERT INTO Ingredient_Custom(idRecipe, idFood, idUser, quantity, unit, isHide) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO Recipe(id, name, type, nbPerson, rating, nbVoter, idUser, idOldUser, idOrigin) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?);
INSERT INTO Recipe_Category(id, name) VALUES (?, ?);
INSERT INTO Recipe_Description(idRecipe, noDescription, description) VALUES (?, ?, ?);
INSERT INTO Recipe_Origin(id, name) VALUES (?, ?);
INSERT INTO Rel_Recipe_Category(idCategory, idRecipe) VALUES (?, ?);
INSERT INTO Rel_User_Recipe(idRecipe, idUser, isFavorite, isForPlanning, rating, isHide) VALUES (?, ?, ?, ?, ?, ?);
INSERT INTO `User`(id, name, pwd, email) VALUES (?, ?, ?, ?);
